[workspace]
members = [ "bin/bye","bin/hello"]

[workspace.dependencies]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
