[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "LIBOPUS_STATIC",
    "LIBSOXR_STATIC",
    "OPENSSL_STATIC"
]

[target.arm-unknown-linux-gnueabihf]
pre-build = ["apt-get update && apt-get install -y libssl-dev"]